FROM eclipse-temurin:17-jdk AS build
WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY gradle.properties .
COPY build-logic build-logic

COPY shared-lib shared-lib
COPY notification-service notification-service

RUN ./gradlew :notification-service:bootJar -x test

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=build /app/notification-service/build/libs/*.jar app.jar

EXPOSE 8086

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
