FROM eclipse-temurin:17-jdk AS build
WORKDIR /app
ENV GRADLE_OPTS="-Xmx256m -Dorg.gradle.daemon=false"

COPY gradlew .
COPY gradle gradle
RUN ./gradlew --version --no-daemon

COPY build.gradle settings.gradle gradle.properties .
COPY build-logic build-logic

COPY notification-service notification-service
RUN ./gradlew :notification-service:bootJar -x test --no-daemon

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/notification-service/build/libs/*.jar app.jar
EXPOSE 8086
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
