server:
  port: 8086

spring:
  application:
    name: notification-service
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group-id
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-offset-reset: earliest
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
      auto.register.schemas: true
      specific.avro.reader: true
      key.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy

logging:
  level:
    com.gnas.starter.notificationservice: DEBUG
