plugins {
    id 'com.gnas.starter.spring-boot-microservice'
    id 'com.avast.gradle.docker-compose' version '0.14.2'
    id "com.github.davidmc24.gradle.plugin.avro" version "1.9.1"
}

repositories {
    maven {
        url "https://packages.confluent.io/maven/"
    }
}

dependencies {
    implementation project(':shared-lib')
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    implementation 'org.springframework.kafka:spring-kafka' 
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'net.javacrumbs.shedlock:shedlock-spring:5.13.0'
    implementation 'net.javacrumbs.shedlock:shedlock-provider-jdbc-template:5.13.0'
    implementation 'org.apache.avro:avro:1.12.1'
    implementation 'io.confluent:kafka-avro-serializer:7.5.1'
    implementation 'org.testng:testng:7.1.0'
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

    runtimeOnly 'org.postgresql:postgresql:42.7.2'
}

dockerCompose {
    useComposeFiles = [
        'docker/docker-compose.yaml',
        'docker/docker-kafka-compose.yaml'
    ]
}


avro {
    stringType = "String"
}

tasks.withType(com.github.davidmc24.gradle.plugin.avro.GenerateAvroJavaTask).configureEach {
    source("src/main/avro")
}

tasks.register('startEnvironment') {
    dependsOn composeUp
}

tasks.register('stopEnvironment') {
    dependsOn composeDownForced
}

tasks.register('startLocal') {
    dependsOn 'startEnvironment', 'bootRun'
    finalizedBy 'stopEnvironment'
}

tasks.named('bootRun') {
    mustRunAfter 'startEnvironment'
}

sourceSets {
    main {
        java {
            srcDirs += "build/generated-main-avro-java"
        }
    }
}