{
  "namespace": "com.gnas.order",
  "type": "record",
  "name": "OrderCreatedEvent",
  "fields": [
    {
      "name": "orderId",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },
    {
      "name": "status",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },
    {
      "name": "products",
      "type": {
        "type": "array",
        "items": {
          "type": "string",
          "avro.java.string": "String"
        }
      },
      "default": []
    },
    {
      "name": "createdAt",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    }
  ]
}