server:
  servlet:
    context-path: /account-service
  port: 8084

database:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:account-db}
  username: ${DB_USERNAME:testuser}
  password: ${DB_PASSWORD:testuser}

spring:
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      ack-mode: manual_immediate
    producer:
      acks: all
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: account-group-id
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
      auto.register.schemas: true
      specific.avro.reader: true
      key.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG