plugins {
    id 'com.gnas.starter.spring-boot-microservice'
    id 'com.avast.gradle.docker-compose' version '0.14.2'
}

dependencies {
    implementation project(':shared-lib')
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    implementation 'org.springframework.kafka:spring-kafka' 
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    runtimeOnly 'org.postgresql:postgresql:42.7.2'
}

dockerCompose {
    useComposeFiles = [
        '/docker/docker-compose.yaml',
        '/docker/docker-kafka-compose.yaml'
    ]
}