FROM eclipse-temurin:17-jdk AS build
WORKDIR /app
ENV GRADLE_OPTS="-Xmx256m -Dorg.gradle.daemon=false"
ARG NEXUS_URL
ENV NEXUS_URL=$NEXUS_URL

COPY gradlew .
COPY gradle gradle
RUN ./gradlew --version --no-daemon

COPY build.gradle settings.gradle gradle.properties .
COPY build-logic build-logic
COPY outbox-lib outbox-lib
COPY shared-lib shared-lib
COPY order-service order-service
RUN ./gradlew :order-service:bootJar -x test --no-daemon

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/order-service/build/libs/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
